services:
  - type: web
    name: glenridescraper
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./public
    envVars:
      - key: NODE_VERSION
        value: 16.x
